openapi: 3.0.0
info:
  title: Albatross internal web API
  version: 0.1.0
paths:
  /api/user/login:
    post:
      operationId: postLogin
      summary: User login
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "john"
                password:
                  type: string
                  example: "password123"
              required:
                - username
                - password
      responses:
        '200':
          description: Successfully authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  loggedIn:
                    type: boolean
                    example: true
                  user:
                    type: object
                    properties:
                      username:
                        type: string
                        example: "john"
                    required:
                      - username
                required:
                  - loggedIn
