openapi: 3.0.0
info:
  title: fortee API
  version: 0.1.0
paths:
  /api/user/login:
    post:
      operationId: postLogin
      summary: User login
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "john"
                password:
                  type: string
                  example: "password123"
              required:
                - username
                - password
      responses:
        '200':
          description: Successfully authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  loggedIn:
                    type: boolean
                    example: true
                  user:
                    type: object
                    properties:
                      username:
                        type: string
                        example: "john"
                    required:
                      - username
                required:
                  - loggedIn
  /api/user/view/{username}:
    get:
      operationId: getUser
      summary: Get a user
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    example: "11111111-1111-1111-1111-111111111111"
                  username:
                    type: string
                    example: "john"
                  avatar_url:
                    type: string
                    example: "/files/_user/11111111-1111-1111-1111-111111111111.jpg"
                required:
                  - uuid
                  - username
                  - avatar_url
        '404':
          description: User not found
