// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserAuthFromUsername = `-- name: GetUserAuthFromUsername :one
SELECT users.user_id, username, display_username, icon_url, is_admin, created_at, user_auth_id, user_auths.user_id, auth_type, password_hash FROM users
JOIN user_auths ON users.user_id = user_auths.user_id
WHERE users.username = $1
`

type GetUserAuthFromUsernameRow struct {
	UserID          int32
	Username        string
	DisplayUsername string
	IconUrl         pgtype.Text
	IsAdmin         bool
	CreatedAt       pgtype.Timestamp
	UserAuthID      int32
	UserID_2        int32
	AuthType        string
	PasswordHash    pgtype.Text
}

func (q *Queries) GetUserAuthFromUsername(ctx context.Context, username string) (GetUserAuthFromUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserAuthFromUsername, username)
	var i GetUserAuthFromUsernameRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayUsername,
		&i.IconUrl,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UserAuthID,
		&i.UserID_2,
		&i.AuthType,
		&i.PasswordHash,
	)
	return i, err
}
